name: task2
description: "Pablo Asenjo Task2"

publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  animated_splash_screen: ^1.3.0
  dartssh2: ^2.8.2
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  shared_preferences: ^2.2.2
  get_it: ^7.2.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

pubspec:
  yaml:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
